from selenium.webdriver.common.by import By
class UrbanRoutesLocator:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    mode_button = (By.CSS_SELECTOR, ".modes-container")
    ask_taxi = (By.CLASS_NAME, 'button.round')
    tariff_picker = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]')
    comfort_tariff = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[5]')
    phone = (By.CLASS_NAME, "np-button")
    add_phone_number = (By.ID, 'phone')
    next_button = (By.CLASS_NAME, "button.full")
    add_code = (By.ID, 'code')
    confirmation_code = (By.CSS_SELECTOR, '.section.active>form>.buttons>:nth-child(1)')
    payment_method = (By.CLASS_NAME, 'pp-button.filled')
    card = (By.CLASS_NAME, 'pp-plus-container')
    card_number = (By.CSS_SELECTOR, '#number.card-input')
    code_card = (By.CSS_SELECTOR, '#code.card-input')
    card_space = (By.CSS_SELECTOR, '.plc')
    add_credit_card = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[2]/form/div[3]/button[1]')
    close_card_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    driver_message = (By.ID, "comment")
    request_order = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[1]')
    blanket_tissues = (By.XPATH,"//*[@id='root']/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span")
    blanket_check = (By.CSS_SELECTOR, '.r-sw > div > input')
    ice_cream = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]')
    reserve_button = (By.CLASS_NAME, "smart-button")
